// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNpPZsBZoI-AQQK0SZ7bwiX9MjaLenMmk',
    appId: '1:784073988375:web:afd8218b4d550e50f67f52',
    messagingSenderId: '784073988375',
    projectId: 'nhgarden-ae870',
    authDomain: 'nhgarden-ae870.firebaseapp.com',
    storageBucket: 'nhgarden-ae870.firebasestorage.app',
    measurementId: 'G-0XMG574HG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XPvDVjj9vBZ0sCLnEBJjOeb1idOOAuA',
    appId: '1:784073988375:android:2c1562dfc7088888f67f52',
    messagingSenderId: '784073988375',
    projectId: 'nhgarden-ae870',
    storageBucket: 'nhgarden-ae870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGTq7A1AJKMC604umg-cbNxMW3eefqsmg',
    appId: '1:784073988375:ios:431137288e3c0dbcf67f52',
    messagingSenderId: '784073988375',
    projectId: 'nhgarden-ae870',
    storageBucket: 'nhgarden-ae870.firebasestorage.app',
    iosBundleId: 'com.example.nhgarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGTq7A1AJKMC604umg-cbNxMW3eefqsmg',
    appId: '1:784073988375:ios:431137288e3c0dbcf67f52',
    messagingSenderId: '784073988375',
    projectId: 'nhgarden-ae870',
    storageBucket: 'nhgarden-ae870.firebasestorage.app',
    iosBundleId: 'com.example.nhgarden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNpPZsBZoI-AQQK0SZ7bwiX9MjaLenMmk',
    appId: '1:784073988375:web:db4bc02c1c9e03dbf67f52',
    messagingSenderId: '784073988375',
    projectId: 'nhgarden-ae870',
    authDomain: 'nhgarden-ae870.firebaseapp.com',
    storageBucket: 'nhgarden-ae870.firebasestorage.app',
    measurementId: 'G-5TDDERC0SV',
  );
}
